import React, { Component } from "react";
import "./Welcome.css";
import { Link } from "react-router-dom";

class Welcome extends Component {
  state = {
    on: false
  };

  toggle = () => {
    this.setState({
      on: !this.state.on
    });
  };

  btn = () => {
    this.btn.focus();
  };

  render() {
    return (
      <div
        className="container"
        /* style={{
          backgroundImage: `url(https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fi.imgur.com%2FOVZmIpg.jpg)`
        }} */
      >
        <div className="main-content">
          <h1 id="game-title">Find your Hero</h1>
          <h1 id="welcome">Card Game</h1>
          <button id="how-to" onClick={this.toggle}>
            Let's see how to play this game
          </button>
          {this.state.on && (
            <h3>
              Two Hero Cards are generated by Game. <br />
              Their ATTACK POWER (AP) score is a combination of POWERSTATS
              <br /> The game compares Attack Powers of Characters and declares
              winner.
              <br /> May the Best Heroes win!
            </h3>
          )}
          <br />
          <Link to="/Card">
            <button
              id="start-game"
              ref={ref => {
                this.btn = ref;
              }}
            >
              Start the game
            </button>
          </Link>
        </div>
      </div>
    );
  }
}

export default Welcome;
